### ISSUE TITLE
No puedo visualizar el ranking

### ISSUE THREAD

**Issue by bi-lriveros** [wwiiddeeweb/bint_word-counter-challenge#1]
Ranking no se puede visualizar, sin embargo se aprecia que si se consumió el api:

`
TypeError: Object.hasOwn is not a function
    at /Users/lriveros/codigo/desafios_banco/sebastian_kravetz/bint_word-counter-challenge/src/api/services/rankgenerator.services.js:9:15
    at Array.reduce (<anonymous>)
    at wordRankingGenerator (/Users/lriveros/codigo/desafios_banco/sebastian_kravetz/bint_word-counter-challenge/src/api/services/rankgenerator.services.js:7:30)
    at textAnalysis (/Users/lriveros/codigo/desafios_banco/sebastian_kravetz/bint_word-counter-challenge/src/api/services/textanalysis.services.js:23:21)
    at ranking (/Users/lriveros/codigo/desafios_banco/sebastian_kravetz/bint_word-counter-challenge/src/api/controllers/apiv1.controllers.js:35:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Object.hasOwn is not a function
    at /Users/lriveros/codigo/desafios_banco/sebastian_kravetz/bint_word-counter-challenge/src/api/services/rankgenerator.services.js:9:15
    at Array.reduce (<anonymous>)
    at wordRankingGenerator (/Users/lriveros/codigo/desafios_banco/sebastian_kravetz/bint_word-counter-challenge/src/api/services/rankgenerator.services.js:7:30)
    at textAnalysis (/Users/lriveros/codigo/desafios_banco/sebastian_kravetz/bint_word-counter-challenge/src/api/services/textanalysis.services.js:23:21)
    at ranking (/Users/lriveros/codigo/desafios_banco/sebastian_kravetz/bint_word-counter-challenge/src/api/controllers/apiv1.controllers.js:35:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

![image](https://user-images.githubusercontent.com/83745886/171224218-acabab99-d9f5-46bf-b80a-5fbcc5778ac3.png)

**Comment by rrooddooxx** [comment]
Hola Luis, acabo de actualizar el servicio de rankgenerator, para intentar resolver el problema dejé de usar el método .hasOwn de la clase Object y cambié a Object.prototype.hasOwnProperty que es el método más universalmente soportado, me imagino que tal vez estabas ejecutando el servidor con una versión más antigua de Node y no la 16.15.0 ? o tal vez el navegador que utilizaste no soporta Object.hasOwn aún? Bueno para salir de dudas hice el cambio, coméntame si ahora puedes hacerlo funcionar.  #https://github.com/wwiiddeeweb/bint_word-counter-challenge/commit/1953f9a4eea474040c2d4fa5dfbfb5730c66cacd
 
<img width="1419" alt="Screen Shot 2022-05-31 at 18 18 02" src="https://user-images.githubusercontent.com/70353160/171293419-7f3a6420-bab6-4e6d-8564-8c0cf2d5f348.png">
